# Generated by Django 4.0.10 on 2023-11-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='calorie_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recipe',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
